version: '3'

services:
 python-webapp:
   build: .
   ports:
     - "5000:5000"
 
 nginx-reverse-proxy:
  build:
    context: .
    dockerfile: nginx.Dockerfile
  ports:
   - "80:80"
  depends_on:
   - python-webapp   